Tambola ticket generator
adityaarakeri/super-scripts pull request #154
Opened 2020-10-04 12:57 UTC by Synster

Adds simple utility to generate tambola tickets

2020-10-05 07:27 UTC, adityaarakeri requested changes

2020-10-05 07:27 UTC, adityaarakeri commented on Tambola_Ticket_Generator/main.py
> +ask (c) 2020. All rights reserved.
please remove copy right, this is free for all repo.

2020-10-05 08:08 UTC, Synster commented on Tambola_Ticket_Generator/main.py
> +ask (c) 2020. All rights reserved.
Removed, thanks

2020-10-06 16:44 UTC, adityaarakeri approved these changes

2020-10-06 16:46 UTC, merged